### ISSUE TITLE
Error installing on Python 3.7.7

### ISSUE THREAD

**Issue by you1anna** [ClearcodeHQ/pytest-mysql#236]
### What action do you want to perform
Install the dependency from setup.py

### What are the results
```
Collecting mysqlclient
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/xxx/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-pip-egg-info-habnr109
         cwd: /private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/9x/4rdlm20d2pb34f7rp5r7yff00000gq/T/pip-install-5ohf69jb/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

### What are the expected results
The package to install successfully

**Comment by fizyk** [comment]
@you1anna the issue you have is from a dependency, and it appears you're missing a system dependency for that, please see: https://github.com/PyMySQL/mysqlclient-python#linux
