### ISSUE TITLE
Compatibility with pytest 7.0

### ISSUE THREAD

**Issue by derfred** [ClearcodeHQ/pytest-mysql#352]
### What action do you want to perform
I upgraded pytest to 7.0

### What are the results

There's a `ImportError` regarding `TempdirFactory` which was removed in 7.0

```
Traceback (most recent call last):

  ....


  File "/usr/local/lib/python3.9/site-packages/pytest_mysql/plugin.py", line 21, in <module>
    from pytest_mysql import factories
  File "/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.9/site-packages/pytest_mysql/factories/__init__.py", line 3, in <module>
    from pytest_mysql.factories.process import mysql_proc
  File "/usr/local/lib/python3.9/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/usr/local/lib/python3.9/site-packages/pytest_mysql/factories/process.py", line 25, in <module>
    from _pytest.tmpdir import TempdirFactory
ImportError: cannot import name 'TempdirFactory' from '_pytest.tmpdir' (/usr/local/lib/python3.9/site-packages/_pytest/tmpdir.py)
```

### What are the expected results
No error

**Comment by fizyk** [comment]
the tmpdir_factory fixture with tmp_path_factory fixture.

The minimum supported pytest version should then be set to 6.2 
ref: https://github.com/ClearcodeHQ/pytest-postgresql/issues/533
